### ISSUE TITLE
Fix alignment of priority icons

### ISSUE THREAD

**Issue by benjaminheng** [cs2103aug2015-f11-2j/main#37]
PSD files: https://drive.google.com/folderview?id=0B1MbIjXD1l4kcF9YcDdqclAtQlE&usp=sharing

Looks fine in the original resolution but idk why it messes up after downscaling.

**Comment by tanweijun** [comment]
It could be due to the downsized resolution having an even number of pixels, so the picture does not have a center pixel and thus the pixel of the picture in the middle can only occupy either the left or right pixel instead of the center one, causing the picture to appear slightly left/right instead of being in the center.

**Comment by tanweijun** [comment]
Improved low and medium priority icons, changed high priority icon.
