### ISSUE TITLE
Make the info view not disappear when typing the keyword

### ISSUE THREAD

**Issue by tanweijun** [cs2103aug2015-f11-2j/main#85]
For example, typing "s" will show the view, but continuing the command to make it "search" the view will disappear, and reappear when the word "search" has been typed fully.

**Comment by subo23** [comment]
i actually did that before by separating all the words(i think i still have the code).
however, Fiona once mentioned what if 'd' -> delete? display?

**Comment by mingxuanlee** [comment]
@tanweijun that's because the parser takes s and search as search, but anything else in between as something else.

Don't think it's necessary though, I vote close

**Comment by tanweijun** [comment]
@mx i think parsing it will make the input better; maybe we can just add more strings like 's', 'se' all the way to 'search' in the parser? Not sure if there is a more efficient way.
@kenny i was thinking if got conflict like d then add parsing after no conflict, like display start from 'di' and delete 'de'.

Sent from my Samsung device

-------- Original message --------

**Comment by mingxuanlee** [comment]
@tanweijun lemme try it now and see if it's more intuitive!

Looks good! 
i've pushed a commit, if it isn't agreeable just undo!

**Comment by benjaminheng** [comment]
I actually did that before but it makes the code very ugly and maintainable

**Comment by benjaminheng** [comment]
Fixed in 0505d8fc86e7d9d9bf4fff4e5c81612fd74866e8
- Typing 's' (registered alias for search) will show the search info view.
- Continuing to type 'sea' will still show the info view, despite 'sea'
  not being a registered alias.
- Pressing space when input is 'sea' will cause 'sea' to expand into
  'search', which is a registered alias for search.

Will close the issue. Please help to test and reopen if necessary.
